# Generated by Django 2.2.2 on 2020-11-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200927_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='last_used',
        ),
    ]
