# Generated by Django 2.2.2 on 2021-01-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(2, 'Completed'), (0, 'TO DO'), (1, 'In Progress')], default=0),
        ),
    ]
